--CREATE INDEX "rocpd_strin_string_c7b9cd_idx" ON "rocpd_string" ("string");
CREATE INDEX "rocpd_api_apiName_id_54bc0a6c" ON "rocpd_api" ("apiName_id");
CREATE INDEX "rocpd_api_args_id_6a626626" ON "rocpd_api" ("args_id");
CREATE UNIQUE INDEX "rocpd_api_ops_api_id_op_id_e7e52317_uniq" ON "rocpd_api_ops" ("api_id", "op_id");
CREATE INDEX "rocpd_api_ops_api_id_f87632ad" ON "rocpd_api_ops" ("api_id");
CREATE INDEX "rocpd_api_ops_op_id_b35ab7c9" ON "rocpd_api_ops" ("op_id");
CREATE INDEX "rocpd_kernelop_codeObject_id_ad04be1d" ON "rocpd_kernelop" ("codeObject_id");
CREATE INDEX "rocpd_kernelop_kernelName_id_96546171" ON "rocpd_kernelop" ("kernelName_id");
CREATE UNIQUE INDEX "rocpd_op_inputSignals_from_op_id_to_op_id_163a30a7_uniq" ON "rocpd_op_inputSignals" ("from_op_id", "to_op_id");
CREATE INDEX "rocpd_op_inputSignals_from_op_id_5fd8f825" ON "rocpd_op_inputSignals" ("from_op_id");
CREATE INDEX "rocpd_op_inputSignals_to_op_id_d34a7779" ON "rocpd_op_inputSignals" ("to_op_id");
CREATE INDEX "rocpd_op_description_id_c8dc8310" ON "rocpd_op" ("description_id");
CREATE INDEX "rocpd_op_opType_id_810aaccd" ON "rocpd_op" ("opType_id");
CREATE INDEX "rocpd_counter_name_id_92b0ed0c" ON "rocpd_counter" ("name_id");
CREATE INDEX "rocpd_counter_op_id_0b4d4b59" ON "rocpd_counter" ("op_id");
